reconfigure:
  name: Reconfigure
  description: Reconfigure a SunPower WebSocket integration.
  fields:
    entry_id:
      name: Config Entry ID
      description: The ID of the config entry to reconfigure.
      required: true
      selector:
        config_entry:
          domain: sunpower_ws
